### ISSUE TITLE
Environmental Recipe Compat [Forge]

### ISSUE THREAD

**Issue by Gatamigo** [Paspartout/UntitledDuckMod#11]
Currently, when playing with both UDM and Abnormal's Mods, duck meat from UDM is not usable for Environmental's duck-based food recipes. 

This is far from the end of the world, but I do believe Environmental accepts OreDict (is it still called oredict I'm behind on the times) specifically the tag "forge:cookedduck". Adding that tag to UDM's cooked duck should automatically allow either duck mob's drops to be used for these recipes and future proof compatibility for other mods that do the same. (I think Pam's Harvestcraft has duck recipes???)

I'm unaware of other mods that include Geese, but it might be worth your time to see if similar oredict entries are floating around out there.

**Comment by Paspartout** [comment]
Should be fixed in 0.2.1
