### ISSUE TITLE
Add feathers and eggs to Forge tags

### ISSUE THREAD

**Issue by KyleHannon** [Paspartout/UntitledDuckMod#15]
Similarly to the cooked_duck tag, I'd love to be able to use duck feathers and duck eggs in other mod recipes (like Create and Pam's HarvestCraft). I think just adding to #forge:feathers and #forge:egg / #forge:eggs would do it?

**Comment by EliasRipley** [comment]
Seconding this as I use Minecolonies Mod and would like the colonists to be able to throw duck / goose eggs into the composter.
https://www.curseforge.com/minecraft/mc-mods/minecolonies
