### ISSUE TITLE
Baby geese don't drop what they are holding when they die

### ISSUE THREAD

**Issue by Fourmisain** [Paspartout/UntitledDuckMod#21]
So geese like to steal things and get aggressive when provoked - I made the mistake of spam throwing eggs, which of course then hit a baby goose for 0 damage, provoking all others in the cage.

Long story short, I died, dropped all my items and didn't immediately know how to get them back (seems dropping seeds on the ground is the go-to way), so I ended up killing them.

Adult geese do drop what they are holding but I learned the hard way that baby geese don't and lost some important items due to that.

**Comment by Paspartout** [comment]
Thanks for reporting! This is due to the fact that baby entites by default don't drop their loot.
I disabled goslings from picking up items now. Since they also don't attack you I think this is the most sensible solution.
Will be fixed in the next release of the mod.

**Comment by Fourmisain** [comment]
Makes sense, although I do think baby foxes do drop the item they are holding, this is just as good of a solution.
Thanks for the quick reply!
