### ISSUE TITLE
Feature Request: Add ability to summon angry geese

### ISSUE THREAD

**Issue by darkphan** [Paspartout/UntitledDuckMod#22]
Loving this mod, the animations and textures are awesome. I think adding the ability to summon angry geese would put it over the top for me, as a content creator. I know they get angry when you hit them, but having viewers spawn in a flock of angry geese would just be something special :)

Thanks in advance!

**Comment by Paspartout** [comment]
Sorry I think this use case is a bit too niche and would require some potentially buggy code. Maybe there is a way to use a command block to fake a player attack though, not sure.
