### ISSUE TITLE
Please add new waterfowl and nest.

### ISSUE THREAD

**Issue by 1235788998753568hfjfu** [Paspartout/UntitledDuckMod#23]
This is a very good mod. Do you plan to join other waterfowls? I hope you can make a nest for waterfowls, like animania farm, to let waterfowls lay eggs in it and hatch their babies.thank you！

**Comment by Paspartout** [comment]
There is another mod in the works which adds swans(not mine though and probably not for fabric) and nests are already kinda covered in #7. I don't have the time to add new waterfowl at the moment but maybe in a future update there will be some.
