### ISSUE TITLE
Can't tame geese

### ISSUE THREAD

**Issue by Zo0m1** [Paspartout/UntitledDuckMod#37]
It says on curseforge and some other places that you can tame geese, but whenever I try doing so it doesn't work, like other mobs all I can do is breed them so thats kind of sad. I'm 99% sure im doing it right... im probably doing something wrong though

**Comment by Paspartout** [comment]
Have you tried seagrass or kelp? I guess the wording on the curseforge is confusing.

**Comment by Zo0m1** [comment]
Oh, I guess I was a little confused. Are seeds supposed to not work?

**Comment by Paspartout** [comment]
They do, but only for breeding not taming. You have to have seperate items foreach action.
