### ISSUE TITLE
new breeds and Male and female

### ISSUE THREAD

**Issue by 1235788998753568hfjfu** [Paspartout/UntitledDuckMod#39]
Please add new breeds and Male and female to ducks and geese

**Comment by 1235788998753568hfjfu** [comment]
Goose
Landes Goose
 
toulouse goose                      

African goose

Alsatian goose

Öland goose

buff grey back goose

african goose

**Comment by 1235788998753568hfjfu** [comment]
duck
Muscovy duck

peking duck

blue swedish duck

saxony duck

**Comment by 1235788998753568hfjfu** [comment]
![yfarm-craft_10](https://user-images.githubusercontent.com/76858579/133959081-9dc73ce6-30cd-4aff-860f-a3b94eb861d4.png)

**Comment by Paspartout** [comment]
Sorry, this wont happen anytime soon. Please don't open new issues about it.
