### ISSUE TITLE
1.17 forge compatible

### ISSUE THREAD

**Issue by gohkenytp** [Paspartout/UntitledDuckMod#41]
Is the ducks mod 1.17 forge compatible?

**Comment by gohkenytp** [comment]
Is there any way to put the Duck mod to Forge 1.17.1? Thanks.

**Comment by Paspartout** [comment]
No, not yet. Maybe in the future.

**Comment by gohkenytp** [comment]
Well I tried it but it cause a error like: "You are using an unstable version of Architectury Loom! Please report any issues found!
"
