### ISSUE TITLE
Messages in log file (no impact noticed)

### ISSUE THREAD

**Issue by xanthian** [Paspartout/UntitledDuckMod#43]
net.minecraft.class_156 Render thread No data fixer registered for untitledduckmod:duck
net.minecraft.class_156 Render thread No data fixer registered for untitledduckmod:duck_egg
net.minecraft.class_156 Render thread No data fixer registered for untitledduckmod:goose
net.minecraft.class_156 Render thread No data fixer registered for untitledduckmod:goose_egg

**Comment by Paspartout** [comment]
These messages are no bugs and you shouldn't have to worry about it.

See this post for example: https://forums.minecraftforge.net/topic/94739-1163-getting-rid-of-data-fixer-error-spam/?do=findComment&comment=433558
