### ISSUE TITLE
[Question] Will it spawn in BYG and Terralith biomes?

### ISSUE THREAD

**Issue by ardissaps** [Paspartout/UntitledDuckMod#65]
Will it spawn in BYG and Terralith biomes?

**Comment by Okabintaro** [comment]
Yes they should. I have not tested it but they should spawn in every biome with grass atm.
Next time please take a look at the mod description and the FAQ on the project page.

**Comment by ardissaps** [comment]
> Yes they should. I have not tested it but they should spawn in every biome with grass atm. Next time please take a look at the mod description and the FAQ on the project page.

How about grass from [Unearthed](https://www.curseforge.com/minecraft/mc-mods/unearthed)?
