### ISSUE TITLE
Make it so the ducks from this mod can replace Environmental's ducks and inherit some of their functions if both mods are present

### ISSUE THREAD

**Issue by Corvus20** [Paspartout/UntitledDuckMod#7]
**Is your feature request related to a problem? Please describe.**
I love Environmental, and I love this mod, but I don't like the overlap that results from having both of them installed.

**Describe the feature you'd like**
Making it so that when both mods are installed, this mod's ducks spawn instead of Environmental's ducks, as well as inheriting the compatibility with Environmental's nest blocks as well as drops/items being acceptable substitutes to environmental's equivalents (meat, eggs, etc.)

**Describe alternatives you've considered**
I could just disable environmental's ducks, but that still leaves some gaps in features, namely the nest compatibility.

**Comment by Paspartout** [comment]
Since environmental is forge only I think it would be too much of a hassle to implement this. Nests maybe implemented in a future update but I am not sure about that.
