### ISSUE TITLE
Dying Ducks Force Disconnect

### ISSUE THREAD

**Issue by TombCruisin** [Paspartout/UntitledDuckMod#73]
v0.6.0 Untitled Duck Mod
On a 1.19 Fabric multiplayer server, if a duck or duckling is killed, players nearby the duck are instantly disconnected, without crashing. The client displays this error:

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@243c134a' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

Players are then able to reconnect without any issues. The duck is dead, with its drops properly spawning in its place. This issue is not present when in singleplayer. Geese are completely unaffected by this issue, singleplayer or multiplayer.

My best guess is the server is having trouble playing the death sound for ducks.

[Dying Ducks Disconnect Server Log.txt](https://github.com/Okabintaro/UntitledDuckMod/files/9477683/Dying.Ducks.Disconnect.Server.Log.txt)

**Comment by Okabintaro** [comment]
Thanks for the report! Should be fixed now in 0.6.1!

**Comment by Bluyidark** [comment]
Can I ask if the fixed version would be available in 1.19 version?
