### ISSUE TITLE
Can I ask if the fixed version would be available in 1.19 version?

### ISSUE THREAD

**Issue by Bluyidark** [Paspartout/UntitledDuckMod#75]
I'm aware of the issue of killing duck forcing disconnect in multiplayer mode, and I'm glad to know it was fixed in the latest update! Though, the latest version seems to be only available in 1.19.2 version, so I wanna ask if it's possible to backport it to 1.19 version as well? Very much thanks!

_Originally posted by @Bluyidark in https://github.com/Okabintaro/UntitledDuckMod/issues/73#issuecomment-1236169683_

**Comment by Okabintaro** [comment]
Sorry, I don't see any reason to maintain support for multiple minor versions of minecraft.
I plan to backport fixes to 1.18.2 eventually but every 1.19 mod should be compatible to 1.19.2, so no reason to stick to an old version of the game.

You can checkout https://github.com/Okabintaro/UntitledDuckMod/tree/v0.6.0-1.19 and cherry-pick https://github.com/Okabintaro/UntitledDuckMod/commit/2a7b744c81a5c76370d04e072db6c0d6edcfa1d0 if you wanna build an old version with the sound fix.
