### ISSUE TITLE
Says I need geckolib3 but I have it already

### ISSUE THREAD

**Issue by PerfectBlueRed** [Paspartout/UntitledDuckMod#81]
**Describe the bug**
I just installed some mods and all their dependencies. This includes the latest version of geckolib3. I checked that it was the Fabric version. However, when I tried to press play from the Fabric launcher, it told me that this mod required geckolib3 version 3.1.6 or later, and that I was missing it. I tried deleting it from my mods folder and re-adding it a few times, but that didn't work. I removed this mod (and kept geckolib3), and then it launched fine.

**To Reproduce**
Try to launch the game using the Fabric modloader. 

**Expected behavior**
Play the game.

**Version**
[Fabric 1.19.2] v0.6.1

**Error Log**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install geckolib3, version 3.1.6 or later.
Unmet dependency listing:
	 - Mod 'Untitled Duck Mod' (untitledduckmod) 0.6.1 requires version 3.1.6 or later of geckolib3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

![image](https://github.com/Okabintaro/UntitledDuckMod/assets/117367610/1e21b8a5-947b-46eb-a5c1-5eceee82d521)

**Comment by Okabintaro** [comment]
You got the wrong version of geckolib there. The one you have is for minecraft 1.20.1.
