### ISSUE TITLE
make them ridable (and steerable)... sailable?

### ISSUE THREAD

**Issue by superon** [Paspartout/UntitledDuckMod#9]
**Is your feature request related to a problem? Please describe.**
Currently no players have been able to mount a waterfowl

**Describe the feature you'd like**
I'd like for players with the arachnid achievement (custom achievement) to be able to mount the waterfowl and ride like jet-skiis :)
Currently Arachnids (an origin from Origins) in my modpack is combined with Inchling origin so is about 1/4 the scale of a regular player, this means if they mount a bout they cannot sea sea.   The sides of the boat are too tall and therefor obscure their vision.
also feel like this would be a more awesome way to travers the open seas.

**Describe alternatives you've considered**
I have asked the mod author of Rats Mischief and an independent developer the similar thing.
I also attempted to create a standalone mounting mod but with all the compromises i had to make with my ability and knowledge it turned into this: https://www.curseforge.com/minecraft/mc-mods/easy-rider
which has 4 major flaws of:
not distinguishing "mob", not discriminating achievement and not being able to direct movement
, so anyone can ride anything, well they can sit on them...
last major flaw it it's forge only and my modpack is fabric based :/

**Additional context**
https://imgur.com/OTwhDOc

note: i did note that you noted that you would NOT be adding feature requests.   i had to ask though incase you thought maybe this was too awesome to not do at some point.

**Comment by Paspartout** [comment]
I really like the idea a lot :)
But I think the use case is too specific for it to be added as a feature to this mod.

Maybe making a seperate mod that adds the functionality would be a better idea, but I am not sure if you can make a ridable and steerable creature using just mixins. I won't have time developing this but feel free to msg me for guidance on the UDM code.
