### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by XanderCrafter** [Paspartout/UntitledDuckMod#93]
**Describe the bug**
Game crashes upon world generation.

**To Reproduce**
Start a world.

**Expected behavior**
Be able to play.

**Version**
Fabric 0.7.0

**Error Log**
Okay

**Additional context**
I run a bunch of mods, and it took ages to figure out that, somehow, Untitled Duck Mod was the culprit for crashing the game.
[crash-2024-07-30_09.57.28-server.txt](https://github.com/user-attachments/files/16430013/crash-2024-07-30_09.57.28-server.txt)

**Comment by Suel-ki** [comment]
c2me conflict, will be fixed in the next version
